[package]
name = "js-snap"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "create_snapshot"
path = "src/create_snapshot.rs"

[dependencies]
lazy_static = "1.4.0"
rusty_v8 = "0.5.1"
